version: '3'

services:
  master:
    build: .
    container_name: mpi_master
    hostname: mpi_master
    ports:
      - "22:22"
    environment:
      - NUM_PROCESSORS=5
      - QUEUE_SERVICE_URL=http://host.docker.internal:7500
      - TRANSACTION_QUEUE=transactions
      - RESULTS_QUEUE=predictions
    volumes:
      - ./mpi:/app/mpi
    command: /bin/bash -c "/usr/sbin/sshd && sleep 5 && mpirun --allow-run-as-root -n 6 -H mpi_master,mpi_worker1,mpi_worker2,mpi_worker3,mpi_worker4,mpi_worker5 python3 prediction_service.py"
    networks:
      - mpi_network

  worker1:
    build: .
    container_name: mpi_worker1
    hostname: mpi_worker1
    volumes:
      - ./mpi:/app/mpi
    command: /usr/sbin/sshd -D
    networks:
      - mpi_network

  worker2:
    build: .
    container_name: mpi_worker2
    hostname: mpi_worker2
    volumes:
      - ./mpi:/app/mpi
    command: /usr/sbin/sshd -D
    networks:
      - mpi_network

  worker3:
    build: .
    container_name: mpi_worker3
    hostname: mpi_worker3
    volumes:
      - ./mpi:/app/mpi
    command: /usr/sbin/sshd -D
    networks:
      - mpi_network

  worker4:
    build: .
    container_name: mpi_worker4
    hostname: mpi_worker4
    volumes:
      - ./mpi:/app/mpi
    command: /usr/sbin/sshd -D
    networks:
      - mpi_network

  worker5:
    build: .
    container_name: mpi_worker5
    hostname: mpi_worker5
    volumes:
      - ./mpi:/app/mpi
    command: /usr/sbin/sshd -D
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge
